### ISSUE TITLE
common/cmm_sanity.c:2170:29: error: passing argument 2 of ‘ether_addr_copy’ from incompatible pointer type

### ISSUE THREAD

**Issue by Mno-hime** [ulli-kroll/mt7610u#1]
Compilation on 4.7.4 kernel (with headers) fails as "common/cmm_sanity.c:2170:29: error: passing argument 2 of ‘ether_addr_copy’ from incompatible pointer type".
`make V=1`:
```
  gcc -Wp,-MD,/usr/src/mt7610u/common/.cmm_sanity.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-redhat-linux/6.2.1/include -I./arch/x86/include -Iarch/x86/include/generated/uapi -Iarch/x86/include/generated  -Iinclude -I./arch/x86/include/uapi -Iarch/x86/include/generated/uapi -I./include/uapi -Iinclude/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -m64 -falign-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mskip-rax-setup -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -maccumulate-outgoing-args -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_SSSE3=1 -DCONFIG_AS_CRC32=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -DCONFIG_AS_SHA1_NI=1 -DCONFIG_AS_SHA256_NI=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -fno-delete-null-pointer-checks -O2 --param=allow-store-data-races=0 -Wframe-larger-than=2048 -fstack-protector-strong -Wno-unused-but-set-variable -Wno-unused-const-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fvar-tracking-assignments -g -pg -mfentry -DCC_USING_FENTRY -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -Werror=incompatible-pointer-types -DCC_HAVE_ASM_GOTO -DSTA_DRIVER_BUILD="\"20141022-1327\"" -g -DAGGREGATION_SUPPORT -DPIGGYBACK_SUPPORT -DWMM_SUPPORT -DLINUX -Wall -Wstrict-prototypes -Wno-trigraphs -DRT28xx_MODE=STA -DCHIPSET=mt7610u -DRESOURCE_PRE_ALLOC -DENHANCED_STAT_DISPLAY -I/usr/src/mt7610u/include -DDOT11_VHT_AC -DCONFIG_STA_SUPPORT -DSCAN_SUPPORT -DDBG -DWPA_SUPPLICANT_SUPPORT -DNATIVE_WPA_SUPPLICANT_SUPPORT -DDOT11_N_SUPPORT -DDOT11N_DRAFT3 -DNEW_RATE_ADAPT_SUPPORT -DSTATS_COUNT_SUPPORT -DRT_CFG80211_SUPPORT -DLED_CONTROL_SUPPORT -DRTMP_TEMPERATURE_TX_ALC -DMT76x0 -DRT65xx -DRLT_MAC -DRLT_RF -DRTMP_MAC_USB -DRTMP_USB_SUPPORT -DRTMP_TIMER_TASK_SUPPORT -DA_BAND_SUPPORT -DRTMP_EFUSE_SUPPORT -DNEW_MBSSID_MODE -DCONFIG_ANDES_SUPPORT -DMT7650 -DMT7630 -DMT7610 -DCONFIG_LITTLE_ENDIAN  -DMODULE  -DKBUILD_BASENAME='"cmm_sanity"'  -DKBUILD_MODNAME='"mt7610u"' -c -o /usr/src/mt7610u/common/cmm_sanity.o /usr/src/mt7610u/common/cmm_sanity.c
/usr/src/mt7610u/common/cmm_sanity.c: In function ‘PeerProbeReqSanity’:
/usr/src/mt7610u/common/cmm_sanity.c:2170:29: error: passing argument 2 of ‘ether_addr_copy’ from incompatible pointer type [-Werror=incompatible-pointer-types]
     ether_addr_copy(pAddr2, &Fr->Hdr.Addr2);
                             ^
In file included from /usr/src/mt7610u/include/os/rt_linux.h:43:0,
                 from /usr/src/mt7610u/include/rtmp_os.h:43,
                 from /usr/src/mt7610u/include/rtmp_comm.h:53,
                 from /usr/src/mt7610u/include/rt_config.h:33,
                 from /usr/src/mt7610u/common/cmm_sanity.c:28:
include/linux/etherdevice.h:274:20: note: expected ‘const u8 * {aka const unsigned char *}’ but argument is of type ‘UCHAR (*)[6] {aka unsigned char (*)[6]}’
 static inline void ether_addr_copy(u8 *dst, const u8 *src)
                    ^~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
scripts/Makefile.build:289: recipe for target '/usr/src/mt7610u/common/cmm_sanity.o' failed
make[2]: *** [/usr/src/mt7610u/common/cmm_sanity.o] Error 1
Makefile:1461: recipe for target '_module_/usr/src/mt7610u' failed
make[1]: *** [_module_/usr/src/mt7610u] Error 2
make[1]: Leaving directory '/usr/src/kernels/4.7.4-200.fc24.x86_64'
Makefile:732: recipe for target 'modules' failed
make: *** [modules] Error 2
```
I use fedora 24 with 4.7.4 kernel.

**Comment by luben93** [comment]
+1

**Comment by ulli-kroll** [comment]
fixed in current git, please test

They are around 20 warnings while compiling, which will be removed in a few days.

**Comment by luben93** [comment]
on 4.7.2-1-ARCH x86_64

/home/luben/Code/mt7610u/os/linux/cfg80211drv.c:527:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
   RT_CMD_STA_IOCTL_SECURITY IoctlSec;
   ^~~~~~~~~~~~~~~~~~~~~~~~~
  CC [M]  /home/luben/Code/mt7610u/common/cmm_mac_usb.o
  CC [M]  /home/luben/Code/mt7610u/common/cmm_data_usb.o
/home/luben/Code/mt7610u/common/cmm_data_usb.c: In function ‘RtmpUSBMgmtKickOut’:
/home/luben/Code/mt7610u/common/cmm_data_usb.c:1009:19: error: passing argument 2 of ‘dump_txinfo’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  dump_txinfo(pAd, pTxInfo);
                   ^~~~~~~
In file included from /home/luben/Code/mt7610u/include/rt_config.h:63:0,
                 from /home/luben/Code/mt7610u/common/cmm_data_usb.c:30:
/home/luben/Code/mt7610u/include/rtmp.h:7853:6: note: expected ‘struct txinfo_nmac_pkt *’ but argument is of type ‘TXINFO_STRUC * {aka union _TXINFO_STRUC *}’
 void dump_txinfo(struct rtmp_adapter*pAd, struct txinfo_nmac_pkt *pTxInfo);
      ^~~~~~~~~~~
/home/luben/Code/mt7610u/common/cmm_data_usb.c:1030:31: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
  pMLMEContext->TransferBuffer = pPacket->data;
                               ^
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:290: /home/luben/Code/mt7610u/common/cmm_data_usb.o] Error 1
make[1]: *** [Makefile:1457: _module_/home/luben/Code/mt7610u] Error 2
make[1]: Leaving directory '/usr/lib/modules/4.7.2-1-ARCH/build'
make: *** [Makefile:733: modules] Error 2

**Comment by ulli-kroll** [comment]
These are "my" warnings ...
I use vanilla kernel for compiling
The problem on your side is
> cc1: some warnings being treated as errors
check for
`-Werror`
in your kernel source tree, 

Fixing these warnings (aka errors) needs some time.
The simple way is to typecast these, which can enable  other problems.
i.e kernel crash in next releases of the driver, if the typecast not resolved.
So I don't do this.

**Comment by ulli-kroll** [comment]
For v4.7 fixed in current git
with v4.8 they are new issues because of the changed cfg80211 API

/me thinking of a something different solution about the drivers ...
