### ISSUE TITLE
Support for Netgear A6210

### ISSUE THREAD

**Issue by diekgait** [ulli-kroll/mt7610u#14]
Hi,

I've loaded the driver but it doesn't recognize my Netgear A6210. How can I make the driver recognize the device?

[  662.553887] mt7610u: loading out-of-tree module taints kernel.
[  662.558252] usbcore: registered new interface driver mt7610u
[  700.059626] usb 2-1: USB disconnect, device number 2
[  702.857851] usb 2-1: new SuperSpeed USB device number 3 using xhci_hcd
[  702.880427] usb 2-1: New USB device found, idVendor=0846, idProduct=9053
[  702.880429] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  702.880430] usb 2-1: Product: A6210
[  702.880431] usb 2-1: Manufacturer: NETGEAR
[  702.880432] usb 2-1: SerialNumber: 100

**Comment by MrEngman** [comment]
Hi diekgait,

You need to use the mt7612 driver.

**Comment by diekgait** [comment]
Hi Mr Engman,

Thanks for your response, the mt7612 doesn't build on my system unfortunately but I already created a ticket for that over there.
[https://github.com/ulli-kroll/mt7612u/issues/7](url)

**Comment by ulli-kroll** [comment]
Closed due wrong driver
