### ISSUE TITLE
Makefile "make install" target

### ISSUE THREAD

**Issue by ffries** [ulli-kroll/mt7610u#20]
This project shows a nice "make install" target:
https://github.com/lwfinger/rtl8188eu/blob/master/Makefile

Would you accept a patch to make install, depmod and modprobe module?

**Comment by ulli-kroll** [comment]
For
make install
currently not. The problem is here if the driver fails loading and the kernel crashes.
You **must** remove this driver "by hand" the resolve boot failures.

**Comment by megatog615** [comment]
Or you could just reboot with the device disconnected(usb unplugged/etc). I think if people are desperate enough to use this driver, then they'll probably take the risk of boot problems in the future.
