### ISSUE TITLE
Point out the rewritten project https://github.com/ulli-kroll/rtl8821au

### ISSUE THREAD

**Issue by kellogsgit** [ulli-kroll/mt7610u#22]
Could you be more explicit and point out to the rewritten driver:
https://github.com/ulli-kroll/rtl8821au

I tried to use mt7610u without luck and shipped back the archer 1U.
Instead I should have used rtl8821au

Write somewhere: 
mt7610u is the original driver, which is not developed and kept for reference only. 
rtl8821au is a complete rewrite of the driver.

**Comment by ulli-kroll** [comment]
NO

TP Link Archer 1U is mt7610u aka Mediatek
D-LINK DWA-171 uses rtl8821au aka Realtek

Please read the thread on LEDE more carefully
