### ISSUE TITLE
Monitor mode doesn't work

### ISSUE THREAD

**Issue by rsegecin** [ulli-kroll/mt7610u#27]
I've tested on the archer 600 T2UH from TP Link and the driver appear as "?????" I did the check kill before I guess it insist to appear because I've another wireless card. I'm a C and C++ programmer may be I could help but I need a push to the right direction.

    $ sudo airmon-ng start wlan0
    
    PHY	Interface	Driver		Chipset
    
    Warn ON: USB
    phy1	wlan0		??????		Ralink Technology, Corp. 
    
    
    ERROR adding monitor mode interface: command failed: Operation not supported (-95)

**Comment by ulli-kroll** [comment]
The cfg80211 implementation from Mediatek in this driver (mt7610u) doesn't support virtual interfaces.
So either wpa_supplicant or airmon-ng can use this device, but not both !

**Comment by rsegecin** [comment]
I've turned wpa_supplicant off and updated the output from airmon-ng above and I'm still getting the same error.

**Comment by ulli-kroll** [comment]
looked at the source from airmon-ng, simple script ..
I think this tool wants to rename/add the device to wlan0mon or similar, which I think is not possible with this driver. And I don't want to dig deeper is this issue.

But tcpdump, airodump-ng are working fire

**Comment by DrArkaneX** [comment]
Ah, I see, so don't use airmon-ng, use iw

i.e.
ifconfig wlan0 down
iw wlan0 set type monitor
ifconfig wlan0 up

sorry, i'm just stuck in airmon mode and didn't realize this part of it.  makes sense now that this device doesn't allow renaming, however what would be the reason this device doesn't like to be renamed?

**Comment by ulli-kroll** [comment]
> Ah, I see, so don't use airmon-ng, use iw
or modify airmon-ng, it's a simple shell script.

If I remember correctly this command is called in airmon-ng
`iw phy0 interface add wlan0mon type monitor`
with some magic behind to check this if this a wifi device.

The problem as I said is the cfg80211 interface in the Mediatek driver.
These function are missing
```
->add_virtual_intf()
->del_virtual_intf()
```
Maybe more.

In contrast mt7612u supports these commands, but no monitor mode.
And to add these functions is out of scoop, mac80211 doesn't need this.
There is some other logic to do this ...

**Comment by rsegecin** [comment]
Until I came across this repository for the mt7610u I've tried many other drivers but noob as I am I didn't bother to check whether the module info mt7610u was actually changing and it apparently it wasn't. So I've copied the mt7610u.ko generated in the build of this project and pasted in `/lib/modules/4.11.2-1-ARCH/kernel/drivers/net/wireless/mt7610u.ko` executed `depmod -a` and rebooted. I still don't know if the driver is properly installed because I can see not only the mt7610u created by Hans but also mt7610u_sta created by Paul Lin (output below). In this configuration I managed to set monitor mode doing `sudo iwconfig wlan0 mode monitor` (noticed now that the module's interface name has changed from the previously 'ra0' to 'wlan0' so I think I'm using the right driver this time). BUT after all this the monitor mode still not working because when I execute a command like 'sudo wash -i wlan0' it doesn't receive any beacons. Reaver also just keep switching channels.

lsmod | grep mt

    mt7610u_sta           864256  0
    mt7610u               618496  1
    cfg80211              520192  5 mt7610u,iwlwifi,mac80211,mt7610u_sta,iwldvm
    usbcore               208896  8 mt7610u,uvcvideo,usbhid,ehci_hcd,mt7610u_sta,xhci_pci,xhci_hcd,ehci_pci

modinfo mt7610u

    filename:       /lib/modules/4.11.2-1-ARCH/kernel/drivers/net/wireless/mt7610u.ko
    firmware:       mt7650u.bin
    firmware:       mt7610u.bin
    description:    MT7610U 80211.ac usb driver
    author:         Hans Ulli Kroll <ulli.kroll@googlemail.com>
    license:        GPL
    alias:          usb:v0E8Dp7650d*dc*dsc*dp*icFFisc02ipFFin*
    alias:          usb:v0E8Dp7630d*dc*dsc*dp*icFFisc02ipFFin*
    alias:          usb:v2357p0105d*dc*dsc*dp*ic*isc*ip*in*
    alias:          usb:v0DF6p0079d*dc*dsc*dp*ic*isc*ip*in*
    alias:          usb:v7392pC711d*dc*dsc*dp*ic*isc*ip*in*
    alias:          usb:v20F4p806Bd*dc*dsc*dp*ic*isc*ip*in*
    alias:          usb:v293Cp5702d*dc*dsc*dp*ic*isc*ip*in*
    alias:          usb:v057Cp8502d*dc*dsc*dp*ic*isc*ip*in*
    alias:          usb:v04BBp0951d*dc*dsc*dp*ic*isc*ip*in*
    alias:          usb:v07B8p7610d*dc*dsc*dp*ic*isc*ip*in*
    alias:          usb:v0586p3425d*dc*dsc*dp*ic*isc*ip*in*
    alias:          usb:v2001p3D02d*dc*dsc*dp*ic*isc*ip*in*
    alias:          usb:v2019pAB31d*dc*dsc*dp*ic*isc*ip*in*
    alias:          usb:v0DF6p0075d*dc*dsc*dp*ic*isc*ip*in*
    alias:          usb:v0B05p17DBd*dc*dsc*dp*ic*isc*ip*in*
    alias:          usb:v0B05p17D1d*dc*dsc*dp*ic*isc*ip*in*
    alias:          usb:v148Fp760Ad*dc*dsc*dp*ic*isc*ip*in*
    alias:          usb:v148Fp761Ad*dc*dsc*dp*ic*isc*ip*in*
    alias:          usb:v7392pB711d*dc*dsc*dp*ic*isc*ip*in*
    alias:          usb:v7392pA711d*dc*dsc*dp*ic*isc*ip*in*
    alias:          usb:v0E8Dp7610d*dc*dsc*dp*ic*isc*ip*in*
    alias:          usb:v13B1p003Ed*dc*dsc*dp*ic*isc*ip*in*
    alias:          usb:v148Fp7610d*dc*dsc*dp*ic*isc*ip*in*
    depends:        cfg80211,usbcore
    vermagic:       4.11.2-1-ARCH SMP preempt mod_unload modversions

modinfo mt7610u_sta

    filename:       /lib/modules/4.11.2-1-ARCH/kernel/drivers/net/wireless/mt7610u_sta.ko
    version:        3.0.0.2
    license:        GPL
    description:    RT2870 Wireless Lan Linux Driver
    author:         Paul Lin <paul_lin@ralinktech.com>
    license:        GPL
    srcversion:     482A8ACE9906E746EC10091
    alias:          usb:v0E8Dp7650d*dc*dsc*dp*icFFisc02ipFFin*
    alias:          usb:v0E8Dp7630d*dc*dsc*dp*icFFisc02ipFFin*
    alias:          usb:v20F4p806Bd*dc*dsc*dp*ic*isc*ip*in*
    alias:          usb:v2019pAB31d*dc*dsc*dp*ic*isc*ip*in*
    alias:          usb:v293Cp5702d*dc*dsc*dp*ic*isc*ip*in*
    alias:          usb:v057Cp8502d*dc*dsc*dp*ic*isc*ip*in*
    alias:          usb:v04BBp0951d*dc*dsc*dp*ic*isc*ip*in*
    alias:          usb:v07B8p7610d*dc*dsc*dp*ic*isc*ip*in*
    alias:          usb:v0586p3425d*dc*dsc*dp*ic*isc*ip*in*
    alias:          usb:v2001p3D02d*dc*dsc*dp*ic*isc*ip*in*
    alias:          usb:v0DF6p0075d*dc*dsc*dp*ic*isc*ip*in*
    alias:          usb:v0B05p17DBd*dc*dsc*dp*ic*isc*ip*in*
    alias:          usb:v0B05p17D1d*dc*dsc*dp*ic*isc*ip*in*
    alias:          usb:v148Fp760Ad*dc*dsc*dp*ic*isc*ip*in*
    alias:          usb:v148Fp761Ad*dc*dsc*dp*ic*isc*ip*in*
    alias:          usb:v7392pB711d*dc*dsc*dp*ic*isc*ip*in*
    alias:          usb:v7392pA711d*dc*dsc*dp*ic*isc*ip*in*
    alias:          usb:v13B1p003Ed*dc*dsc*dp*ic*isc*ip*in*
    alias:          usb:v0E8Dp7610d*dc*dsc*dp*ic*isc*ip*in*
    alias:          usb:v148Fp7610d*dc*dsc*dp*ic*isc*ip*in*
    depends:        cfg80211,usbcore
    vermagic:       4.11.2-1-ARCH SMP preempt mod_unload modversions 
    parm:           mac:wireless mac addr (charp)
    parm:           debug:log verbosity level (0: off, 1: error only [default], 2: warnings, 3: trace, 4: info, 5: loud) (long)

iwconfig

    wlp11s0   IEEE 802.11  ESSID:"Rinaldi"  
              Mode:Managed  Frequency:2.412 GHz  Access Point: D7:3A:35:59:10:XX   
              Bit Rate=1 Mb/s   Tx-Power=14 dBm   
              Retry short limit:7   RTS thr:off   Fragment thr:off
              Encryption key:off
              Power Management:off
              Link Quality=50/70  Signal level=-60 dBm  
              Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
              Tx excessive retries:35  Invalid misc:218   Missed beacon:0

    enp10s0   no wireless extensions.

    lo        no wireless extensions.

    wlan0     Ralink STA  ESSID:""  Nickname:""
              Mode:Monitor  Frequency=2.422 GHz  Access Point: Not-Associated   
              Bit Rate:1 Mb/s   
              RTS thr:off   Fragment thr:off
              Encryption key:off
              Link Quality=10/100  Signal level:0 dBm  Noise level:0 dBm
              Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
              Tx excessive retries:0  Invalid misc:0   Missed beacon:0

sudo wash -i wlan0

    ash v1.5.2 WiFi Protected Setup Scan Tool
    Copyright (c) 2011, Tactical Network Solutions, Craig Heffner <cheffner@tacnetsol.com>
    mod by t6_x <t6_x@hotmail.com> & DataHead & Soxrok2212 & Wiire & kib0rg

    BSSID              Channel  RSSI  WPS Version  WPS Locked  ESSID
    --------------------------------------------------------------------------------------
    [stops here forever]

**Comment by ulli-kroll** [comment]
Please use only one driver and remove the unused from
`/lib/modules/`
I prefer mine, because the memory leak is fixed some time ago.

Please check if monitor mode is working with tcpdump
```
buildroot ~ # lsmod 
Module                  Size  Used by    Tainted: G  
mt7610u               516096  1 
mac80211              417792  0 
cfg80211              221184  2 mt7610u,mac80211
rfkill                 20480  1 cfg80211
buildroot ~ # iwconfig wlan0
wlan0     Ralink STA  ESSID:""  Nickname:""
          Mode:Monitor  Frequency=5.18 GHz  Access Point: Not-Associated   
          Bit Rate:1 Mb/s   
          RTS thr:off   Fragment thr:off
          Encryption key:off
          Link Quality=10/100  Signal level:0 dBm  Noise level:0 dBm
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

buildroot ~ # tcpdump  -i wlan0 
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on wlan0, link-type PRISM_HEADER (802.11 plus Prism header), capture size 262144 bytes
15:42:33.002161 Beacon (Sternenhimmel) [1.0* 2.0* 5.5* 11.0* 6.0* 9.0 12.0* 18.0 Mbit] ESS CH: 1, PRIVACY
15:42:33.034279 Beacon (FBI Surveillance Van 42) [1.0* 2.0* 5.5* 11.0* 6.0* 9.0 12.0* 18.0 Mbit] ESS CH: 1, PRIVACY
15:42:33.063405 Beacon (EasyBox-DCBA48) [1.0* 2.0* 5.5* 11.0* 9.0 18.0 36.0 54.0 Mbit] ESS CH: 1, PRIVACY
15:42:33.082029 Beacon (FRITZ!Box 7272) [1.0* 2.0* 5.5* 11.0* 6.0* 9.0 12.0* 18.0 Mbit] ESS CH: 1, PRIVACY
15:42:33.104525 Beacon (Sternenhimmel) [1.0* 2.0* 5.5* 11.0* 6.0* 9.0 12.0* 18.0 Mbit] ESS CH: 1, PRIVACY
15:42:33.136646 Beacon (FBI Surveillance Van 42) [1.0* 2.0* 5.5* 11.0* 6.0* 9.0 12.0* 18.0 Mbit] ESS CH: 1, PRIVACY
15:42:33.165768 Beacon (EasyBox-DCBA48) [1.0* 2.0* 5.5* 11.0* 9.0 18.0 36.0 54.0 Mbit] ESS CH: 1, PRIVACY
15:42:33.182015 Beacon (FRITZ!Box 7272) [1.0* 2.0* 5.5* 11.0* 6.0* 9.0 12.0* 18.0 Mbit] ESS CH: 1, PRIVACY
15:42:33.207141 Beacon (Sternenhimmel) [1.0* 2.0* 5.5* 11.0* 6.0* 9.0 12.0* 18.0 Mbit] ESS CH: 1, PRIVACY
15:42:33.268141 Beacon (EasyBox-DCBA48) [1.0* 2.0* 5.5* 11.0* 9.0 18.0 36.0 54.0 Mbit] ESS CH: 1, PRIVACY
15:42:33.286757 Beacon (FRITZ!Box 7272) [1.0* 2.0* 5.5* 11.0* 6.0* 9.0 12.0* 18.0 Mbit] ESS CH: 1, PRIVACY
15:42:33.311128 Beacon (Sternenhimmel) [1.0* 2.0* 5.5* 11.0* 6.0* 9.0 12.0* 18.0 Mbit] ESS CH: 1, PRIVACY
15:42:33.341379 Beacon (FBI Surveillance Van 42) [1.0* 2.0* 5.5* 11.0* 6.0* 9.0 12.0* 18.0 Mbit] ESS CH: 1, PRIVACY

```

I use buildroot to avoid any interferences

**Comment by rsegecin** [comment]
Thank you very much Kroll, it did work with tcpdump it start receive beacons and probes. This driver is just not compatible with wash and reaver programs I guess. I'll bother [Grabiel Couto](https://github.com/gabrielrcouto/reaver-wps) now because he wrote an updated version of the reaver and I'll try to make compatible with mt7610u driver.  I know I'm over my head with this but I'll give a try. 

Thank you very much.

**Comment by imzyxwvu** [comment]
I tried to set up an fake AP via airbase-ng with monitor mode. No error reported but I was unable to find the fake AP. Is the driver not transmitting packets in monitor mode?
