### ISSUE TITLE
error: implicit declaration 

### ISSUE THREAD

**Issue by pauledd** [ulli-kroll/mt7610u#36]
Hi

I try to compile the driver on a raspberry pi 2 (gcc-Version 5.4.0) . But I get an error:

> bitfield.h:63:3: error: implicit declaration of function '__BUILD_BUG_ON_NOT_POWER_OF_2' [-Werror=implicit-function-declaration]
full log:

> 
> pi@astro ~/build/mt7610u $ LANG=en make -j4 ARCH=arm
> make ARCH=arm CROSS_COMPILE= -C /lib/modules/4.4.20-raspberrypi-v7+/build M=/mnt/rp/srcrp/build/mt7610u modules
> make[1]: Entering directory '/mnt/rp/srcrp/build/linux-4.4.9999-raspberrypi'
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/os/linux/rt_profile.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/sta/assoc.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/sta/auth.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/sta/auth_rsp.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/sta/sync.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/sta/sanity.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/sta/rtmp_data.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/sta/connect.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/sta/wpa.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/sta/sta_cfg.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/mgmt/mgmt_vht.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/common/vht.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/common/crypt_md5.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/common/crypt_sha2.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/common/crypt_hmac.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/common/crypt_aes.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/common/crypt_arc4.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/common/mlme.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/common/cmm_wep.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/common/action.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/common/cmm_data.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/common/rtmp_init.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/common/rtmp_init_inf.o
> /mnt/rp/srcrp/build/mt7610u/common/rtmp_init.c: In function 'NICInitializeAsic.part.0':
> /mnt/rp/srcrp/build/mt7610u/common/rtmp_init.c:1113:1: warning: the frame size of 2032 bytes is larger than 1024 bytes [-Wframe-larger-than=]
>  }
>  ^
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/common/cmm_tkip.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/common/cmm_aes.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/common/cmm_sync.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/common/cmm_sanity.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/common/cmm_info.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/common/cmm_cfg.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/common/cmm_wpa.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/common/cmm_radar.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/common/spectrum.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/common/rtmp_timer.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/common/rt_channel.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/common/cmm_profile.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/common/cmm_asic.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/common/scan.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/common/cmm_cmd.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/common/uapsd.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/common/ps.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/rate_ctrl/ra_ctrl.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/rate_ctrl/alg_legacy.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/rate_ctrl/alg_ags.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/chips/rtmp_chip.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/common/txpower.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/mac/rtmp_mac.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/mgmt/mgmt_entrytb.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/phy/rtmp_phy.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/phy/rlt_phy.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/phy/rlt_rf.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/rate_ctrl/alg_grp.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/common/ba_action.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/mgmt/mgmt_ht.o
> /mnt/rp/srcrp/build/mt7610u/rate_ctrl/alg_grp.c: In function 'StaQuickResponeForRateUpExecAdapt':
> /mnt/rp/srcrp/build/mt7610u/rate_ctrl/alg_grp.c:1064:38: warning: comparison of constant '2' with boolean expression is always false [-Wbool-compare]
>    else if (pAd->CommonCfg.TrainUpRule==2 && Rssi<=pAd->CommonCfg.TrainUpRuleRSSI)
>                                       ^
> /mnt/rp/srcrp/build/mt7610u/rate_ctrl/alg_grp.c:1068:38: warning: comparison of constant '3' with boolean expression is always false [-Wbool-compare]
>    else if (pAd->CommonCfg.TrainUpRule==3 && Rssi<=pAd->CommonCfg.TrainUpRuleRSSI)
>                                       ^
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/common/rt_os_util.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/os/linux/sta_ioctl.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/os/linux/rt_linux.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/os/linux/rt_main_dev.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/common/rt_led.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/os/linux/cfg80211.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/os/linux/cfg80211drv.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/common/cmm_mac_usb.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/common/cmm_data_usb.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/common/rtusb_io.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/common/rtusb_data.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/common/rtusb_bulk.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/os/linux/rt_usb.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/common/rt_rf.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/chips/rt65xx.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/chips/mt76x0.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/mac/ral_nmac.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/mcu/mcu.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/mcu/mcu_and.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/os/linux/rt_usb_util.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/os/linux/usb_main_dev.o
>   CC [M]  /mnt/rp/srcrp/build/mt7610u/common/frq_cal.o
> In file included from /mnt/rp/srcrp/build/mt7610u/mcu/mcu_and.c:30:0:
> /mnt/rp/srcrp/build/mt7610u/mcu/mcu_and.c: In function 'mt7610u_dma_skb_wrap':
> /mnt/rp/srcrp/build/mt7610u/include/bitfield.h:63:3: error: implicit declaration of function '__BUILD_BUG_ON_NOT_POWER_OF_2' [-Werror=implicit-function-declaration]
>    __BUILD_BUG_ON_NOT_POWER_OF_2((_mask) +   \
>    ^
> /mnt/rp/srcrp/build/mt7610u/include/bitfield.h:90:3: note: in expansion of macro '__BF_FIELD_CHECK'
>    __BF_FIELD_CHECK(_mask, 0ULL, _val, "FIELD_PREP: "); \
>    ^
> /mnt/rp/srcrp/build/mt7610u/mcu/mcu_and.c:94:3: note: in expansion of macro 'FIELD_PREP'
>    FIELD_PREP(MT_TXD_INFO_LEN, round_up(skb->len, 4)) |
>    ^
> cc1: some warnings being treated as errors
> scripts/Makefile.build:258: recipe for target '/mnt/rp/srcrp/build/mt7610u/mcu/mcu_and.o' failed
> make[2]: *** [/mnt/rp/srcrp/build/mt7610u/mcu/mcu_and.o] Error 1
> Makefile:1385: recipe for target '_module_/mnt/rp/srcrp/build/mt7610u' failed
> make[1]: *** [_module_/mnt/rp/srcrp/build/mt7610u] Error 2
> make[1]: Leaving directory '/mnt/rp/srcrp/build/linux-4.4.9999-raspberrypi'
> Makefile:385: recipe for target 'modules' failed
> make: *** [modules] Error 2

any ideas ?

**Comment by karlstav** [comment]
For some reason they changed it from `BUILD_BUG_ON_NOT_POWER_OF_2` to `__BUILD_BUG_ON_NOT_POWER_OF_2` in kernel v4.9. So you need to be on 4.9 or higher. Maybe there are some other work around as well.

**Comment by pauledd** [comment]
Ok, thank you. I will upgrade.
