### ISSUE TITLE
This driver can support Raspbian Kernel version 4.9??

### ISSUE THREAD

**Issue by AAV514** [ulli-kroll/mt7610u#39]
This driver can support Raspbian Kernel version 4.9??

**Comment by ulli-kroll** [comment]
I don't know
last time someone emailed me about a fixed bug in monitor mode on mt7610u running on some random raspberry pi.

**Comment by mraspaud** [comment]
@AAV514 I just compile it on Raspbian stretch, kernel 4.9 and it seems to work:

`ARCH=arm make`

Good luck!
