### ISSUE TITLE
Build error: 'struct net_device’ has no member named ‘wireless_handlers'

### ISSUE THREAD

**Issue by kgroombr** [ulli-kroll/mt7610u#40]
Using kernel 4.12.8 I am getting the appended error.  Googling indicated that I had to enable CONFIG_WIRELESS_EXT in the kernel, but it appears that directly enabling this option is no longer available on only drivers that require it will enable this.

Read the docs just to be sure I wasn't a moron and I believe I did everything correctly.

  CC [M]  /var/tmp/mt7610u-master/os/linux/rt_linux.o
/var/tmp/mt7610u-master/os/linux/rt_linux.c: In function ‘RtmpOSNetDevAttach’:
/var/tmp/mt7610u-master/os/linux/rt_linux.c:1233:11: error: ‘struct net_device’ has no member named ‘wireless_handlers’; did you mean ‘rx_handler’?
    pNetDev->wireless_handlers = &rt28xx_iw_handler_def;
           ^~
make[2]: *** [scripts/Makefile.build:303: /var/tmp/mt7610u-master/os/linux/rt_linux.o] Error 1
make[1]: *** [Makefile:1515: _module_/var/tmp/mt7610u-master] Error 2
make[1]: Leaving directory '/usr/src/linux-4.12.8-gentoo'
make: *** [Makefile:385: modules] Error 2

**Comment by ulli-kroll** [comment]
> Read the docs just to be sure I wasn't a moron and I believe I did everything correctly.

Please judge yourself ...

```
$ git describe
v4.12.8
git ggrep CFG80211_WEXT net/wireless/Kconfig
net/wireless/Kconfig:6: depends on CFG80211_WEXT || WIRELESS_EXT
net/wireless/Kconfig:174:config CFG80211_WEXT
net/wireless/Kconfig:175:       bool "cfg80211 wireless extensions compatibility" if !CFG80211_WEXT_EXPORT
net/wireless/Kconfig:178:       default y if CFG80211_WEXT_EXPORT
net/wireless/Kconfig:183:config CFG80211_WEXT_EXPORT
```
you have to enable
CFG80211_WEXT

**Comment by kgroombr** [comment]
That was the first item I checked.

I have that enabled.  Here is a snippet from my /boot/config-4.12.8-gentoo in boot showing that my kernel was built with that option:

# CONFIG_STREAM_PARSER is not set
CONFIG_FIB_RULES=y
CONFIG_WIRELESS=y
CONFIG_WEXT_CORE=y
CONFIG_WEXT_PROC=y
CONFIG_CFG80211=m
# CONFIG_NL80211_TESTMODE is not set
# CONFIG_CFG80211_DEVELOPER_WARNINGS is not set
CONFIG_CFG80211_DEFAULT_PS=y
# CONFIG_CFG80211_INTERNAL_REGDB is not set
CONFIG_CFG80211_CRDA_SUPPORT=y
CONFIG_CFG80211_WEXT=y
# CONFIG_LIB80211 is not set

**Comment by ulli-kroll** [comment]
/boot/config-4.12.8-gentoo != /usr/src/linux-4.12.8-gentoo/.config

**Please** check your (running) kernel config 

```
buildroot ~ # uname -a
Linux buildroot 4.12.8 #74 SMP Sat Aug 26 17:15:51 CEST 2017 x86_64 GNU/Linux
buildroot ~ # zcat /proc/config.gz | grep WEXT
CONFIG_WEXT_CORE=y
CONFIG_WEXT_PROC=y
CONFIG_WEXT_SPY=y
CONFIG_WEXT_PRIV=y
CONFIG_CFG80211_WEXT=y
buildroot ~ # lsmod 
Module                  Size  Used by    Tainted: G  
mt7610u               516096  0 
mac80211              417792  0 
cfg80211              225280  2 mt7610u,mac80211
rfkill                 20480  1 cfg80211

```

**Comment by kgroombr** [comment]
Thanks for taking the time to help.  Here is the requested output:

zcat /proc/config.gz | grep WEXT 
CONFIG_WEXT_CORE=y
CONFIG_WEXT_PROC=y
CONFIG_CFG80211_WEXT=y

**Comment by ulli-kroll** [comment]
You DON'T understand ...

Your running config is fine, but your config in
`/usr/src/linux-4.12.8-gentoo/.config`
is missing 
CONFIG_CFG80211_WEXT

either copy this from your /boot or use the running config

This issue is CLOSED

**Comment by kgroombr** [comment]
I do understand, and sorry to be a pain.  Gentoo does not come with prebuilt kernels.  I just downloaded kernel 4.12.9-gentoo source, built, installed, and booted from this kernel.  Here are all the commands to show that this option is configured correctly:

Nomad boot # uname -a
Linux nomad 4.12.9-gentoo #1 SMP PREEMPT Fri Aug 25 20:52:36 EDT 2017 x86_64 Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz GenuineIntel GNU/Linux
nomad boot # grep WEXT /usr/src/linux-4.12.9-gentoo/.config
CONFIG_WEXT_CORE=y
CONFIG_WEXT_PROC=y
CONFIG_CFG80211_WEXT=y
nomad boot # zcat /proc/config.gz | grep WEXT
CONFIG_WEXT_CORE=y
CONFIG_WEXT_PROC=y
CONFIG_CFG80211_WEXT=y
nomad boot # grep WEXT config-4.12.9-gentoo
CONFIG_WEXT_CORE=y
CONFIG_WEXT_PROC=y
CONFIG_CFG80211_WEXT=y

And after this install, I still receive the same error when attempting to build this module.

I know problems like this can be difficult to track down, but what I can do is create an account for you and allow you to log directly into this system and you can take a look.

**Comment by kgroombr** [comment]
I wanted to add an update to this since the maintainer of the code jumps to conclusions before he knows the facts and proclaims to have the answer, but be totally wrong.  I would be leery of using code maintained by someone that doesn't have a clue on the proper kernel options that must be selected in order for this module to properly compile and install.

The issue is exactly what I put in my first post.  The kernel option "CONFIG_WIRELESS_EXT" must be enabled.  The problem is that this kernel option can't be directly enabled in recent kernels, so a kernel option must be selected which depends on this.

One option that will do this with the 4.13 Gentoo kernel source is:

`Staging Drivers->Realtek RTL8188EU Wireless LAN NIC driver->Realtek RTL8188EU AP mode`

Even if you don't need this driver, you have to select this, or one that depends on the "CONFIG_WIRELESS_EXT" kernel option.
