### ISSUE TITLE
Build error on Ubuntu 17.10 Beta 2, kernel 4.13.0

### ISSUE THREAD

**Issue by vintersorgh** [ulli-kroll/mt7610u#43]
ackan@mackan-pc:~/mt7610u$ make
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.13.0-12-generic/build M=/home/mackan/mt7610u modules
make[1]: Går till katalogen ”/usr/src/linux-headers-4.13.0-12-generic”
  CC [M]  /home/mackan/mt7610u/sta/assoc.o
  CC [M]  /home/mackan/mt7610u/sta/auth.o
  CC [M]  /home/mackan/mt7610u/sta/auth_rsp.o
  CC [M]  /home/mackan/mt7610u/sta/sync.o
  CC [M]  /home/mackan/mt7610u/sta/sanity.o
  CC [M]  /home/mackan/mt7610u/sta/rtmp_data.o
  CC [M]  /home/mackan/mt7610u/sta/connect.o
  CC [M]  /home/mackan/mt7610u/sta/wpa.o
  CC [M]  /home/mackan/mt7610u/sta/sta_cfg.o
  CC [M]  /home/mackan/mt7610u/mgmt/mgmt_vht.o
  CC [M]  /home/mackan/mt7610u/common/vht.o
  CC [M]  /home/mackan/mt7610u/common/crypt_md5.o
  CC [M]  /home/mackan/mt7610u/common/crypt_sha2.o
  CC [M]  /home/mackan/mt7610u/common/crypt_hmac.o
  CC [M]  /home/mackan/mt7610u/common/crypt_aes.o
  CC [M]  /home/mackan/mt7610u/common/crypt_arc4.o
  CC [M]  /home/mackan/mt7610u/common/mlme.o
  CC [M]  /home/mackan/mt7610u/common/cmm_wep.o
  CC [M]  /home/mackan/mt7610u/common/action.o
  CC [M]  /home/mackan/mt7610u/common/cmm_data.o
  CC [M]  /home/mackan/mt7610u/common/rtmp_init.o
/home/mackan/mt7610u/common/rtmp_init.c: In function ‘NICInitializeAsic.part.0’:
/home/mackan/mt7610u/common/rtmp_init.c:1113:1: warning: the frame size of 2048 bytes is larger than 1024 bytes [-Wframe-larger-than=]
 }
 ^
  CC [M]  /home/mackan/mt7610u/common/rtmp_init_inf.o
  CC [M]  /home/mackan/mt7610u/common/cmm_tkip.o
  CC [M]  /home/mackan/mt7610u/common/cmm_aes.o
  CC [M]  /home/mackan/mt7610u/common/cmm_sync.o
  CC [M]  /home/mackan/mt7610u/common/cmm_sanity.o
  CC [M]  /home/mackan/mt7610u/common/cmm_info.o
  CC [M]  /home/mackan/mt7610u/common/cmm_cfg.o
  CC [M]  /home/mackan/mt7610u/common/cmm_wpa.o
  CC [M]  /home/mackan/mt7610u/common/cmm_radar.o
  CC [M]  /home/mackan/mt7610u/common/spectrum.o
In file included from ./include/linux/bitmap.h:8:0,
                 from ./include/linux/cpumask.h:11,
                 from ./arch/x86/include/asm/cpumask.h:4,
                 from ./arch/x86/include/asm/msr.h:10,
                 from ./arch/x86/include/asm/processor.h:20,
                 from ./arch/x86/include/asm/cpufeature.h:4,
                 from ./arch/x86/include/asm/thread_info.h:52,
                 from ./include/linux/thread_info.h:37,
                 from ./arch/x86/include/asm/preempt.h:6,
                 from ./include/linux/preempt.h:80,
                 from ./include/linux/spinlock.h:50,
                 from ./include/linux/seqlock.h:35,
                 from ./include/linux/time.h:5,
                 from ./include/linux/stat.h:18,
                 from ./include/linux/module.h:10,
                 from /home/mackan/mt7610u/include/os/rt_linux.h:31,
                 from /home/mackan/mt7610u/include/rtmp_os.h:43,
                 from /home/mackan/mt7610u/include/rtmp_comm.h:44,
                 from /home/mackan/mt7610u/include/rt_config.h:33,
                 from /home/mackan/mt7610u/common/spectrum.c:28:
/home/mackan/mt7610u/common/spectrum.c: In function ‘Set_MeasureReq_Proc’:
./include/linux/string.h:324:9: warning: argument 1 null where non-null expected [-Wnonnull]
  return __builtin_memmove(p, q, size);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/string.h:324:9: note: in a call to built-in function ‘__builtin_memmove’
  CC [M]  /home/mackan/mt7610u/common/rtmp_timer.o
  CC [M]  /home/mackan/mt7610u/common/rt_channel.o
  CC [M]  /home/mackan/mt7610u/common/cmm_profile.o
  CC [M]  /home/mackan/mt7610u/common/cmm_asic.o
  CC [M]  /home/mackan/mt7610u/common/scan.o
  CC [M]  /home/mackan/mt7610u/common/cmm_cmd.o
  CC [M]  /home/mackan/mt7610u/common/uapsd.o
  CC [M]  /home/mackan/mt7610u/common/ps.o
  CC [M]  /home/mackan/mt7610u/rate_ctrl/ra_ctrl.o
  CC [M]  /home/mackan/mt7610u/rate_ctrl/alg_legacy.o
  CC [M]  /home/mackan/mt7610u/rate_ctrl/alg_ags.o
  CC [M]  /home/mackan/mt7610u/chips/rtmp_chip.o
  CC [M]  /home/mackan/mt7610u/common/txpower.o
  CC [M]  /home/mackan/mt7610u/mac/rtmp_mac.o
  CC [M]  /home/mackan/mt7610u/mgmt/mgmt_entrytb.o
  CC [M]  /home/mackan/mt7610u/phy/rtmp_phy.o
  CC [M]  /home/mackan/mt7610u/phy/rlt_phy.o
  CC [M]  /home/mackan/mt7610u/phy/rlt_rf.o
  CC [M]  /home/mackan/mt7610u/rate_ctrl/alg_grp.o
  CC [M]  /home/mackan/mt7610u/common/ba_action.o
  CC [M]  /home/mackan/mt7610u/mgmt/mgmt_ht.o
  CC [M]  /home/mackan/mt7610u/common/rt_os_util.o
  CC [M]  /home/mackan/mt7610u/os/linux/sta_ioctl.o
In file included from ./include/linux/bitmap.h:8:0,
                 from ./include/linux/cpumask.h:11,
                 from ./arch/x86/include/asm/cpumask.h:4,
                 from ./arch/x86/include/asm/msr.h:10,
                 from ./arch/x86/include/asm/processor.h:20,
                 from ./arch/x86/include/asm/cpufeature.h:4,
                 from ./arch/x86/include/asm/thread_info.h:52,
                 from ./include/linux/thread_info.h:37,
                 from ./arch/x86/include/asm/preempt.h:6,
                 from ./include/linux/preempt.h:80,
                 from ./include/linux/spinlock.h:50,
                 from ./include/linux/seqlock.h:35,
                 from ./include/linux/time.h:5,
                 from ./include/linux/stat.h:18,
                 from ./include/linux/module.h:10,
                 from /home/mackan/mt7610u/include/os/rt_linux.h:31,
                 from /home/mackan/mt7610u/include/rtmp_os.h:43,
                 from /home/mackan/mt7610u/include/rtmp_comm.h:44,
                 from /home/mackan/mt7610u/os/linux/sta_ioctl.c:30:
In function ‘memcpy’,
    inlined from ‘rt_ioctl_iwaplist’ at /home/mackan/mt7610u/os/linux/sta_ioctl.c:546:2:
./include/linux/string.h:305:4: error: call to ‘__read_overflow2’ declared with attribute error: detected read beyond size of object passed as 2nd parameter
    __read_overflow2();
    ^~~~~~~~~~~~~~~~~~
scripts/Makefile.build:302: receptet för målet ”/home/mackan/mt7610u/os/linux/sta_ioctl.o” misslyckades
make[2]: *** [/home/mackan/mt7610u/os/linux/sta_ioctl.o] Fel 1
Makefile:1546: receptet för målet ”_module_/home/mackan/mt7610u” misslyckades
make[1]: *** [_module_/home/mackan/mt7610u] Fel 2
make[1]: Lämnar katalogen ”/usr/src/linux-headers-4.13.0-12-generic”
Makefile:371: receptet för målet ”modules” misslyckades
make: *** [modules] Fel 2

Anything related to https://patchwork.kernel.org/patch/9885051/ or https://github.com/lwfinger/rtl8723au/issues/66 ?

**Comment by ulli-kroll** [comment]
rather latter one.
FORTIFY_SOURCE is introduced in  v4.13 from the kernel self protecting team.

Need some time to fix this, they are maybe more errors like in this driver on mt7612u

**Comment by ulli-kroll** [comment]
Please check current git
and close this isssue ..
