### ISSUE TITLE
advice asked: RT3572 injection doesn't work in chans > 64

### ISSUE THREAD

**Issue by rofl0r** [ulli-kroll/mt7610u#49]
sorry if this is not the right place to ask, but since you're very familiar with ralink drivers, maybe you have an idea (or already found the bug) why RT3572 (using rt2800usb driver) can't inject packets in channels > 64 ? monitor mode works though. this happens on linux 4.13, and earlier (afaik). not sure about bleeding edge.

**Comment by rofl0r** [comment]
btw, the same happens with iwl3945 driver, but not with the hackjob rtl8812au driver from github.com/aircrack-ng

**Comment by ulli-kroll** [comment]
Hi,
I assume rtl2800usb is upstream ??
which band uses RT3572 
2.4 GHz or 5 GHz ?
wikidevi page ?

**Comment by rofl0r** [comment]
yes, it is supported upstream. it uses 2.4 Ghz and 5GHz, and i am talking about 5 GHz band here.

https://wikidevi.com/wiki/ALFA_Network_AWUS052NH
https://wikidevi.com/wiki/Ralink

> RT3572 | USB 2.0 | abgn | 2x2:2 | 2009-05-11 | . | 36 devices | 6 devices | PBriefPPage

**Comment by ulli-kroll** [comment]
Some more question ...
but this injection is working for channels < 64 ?

**Comment by rofl0r** [comment]
yes, it works in all chans < 64

**Comment by ulli-kroll** [comment]
And with monitor mode if channels > 64 ??
If yes ... strange ...

**Comment by rofl0r** [comment]
yes, indeed.
however, it's been reported to me that it works in kernel 4.14. if i get around i'll try it myself and if it works try to find the commit that fixed it. since both iwl3945 and rt2800usb have the issue, i suspect its a bug somewhere in the nl80211 stack; and since the astsam rtl8812au driver uses wext, that is probably the reason it was not affected.

**Comment by rofl0r** [comment]
turned out it was a crda regdom issue 

> the thing was due to reg settings. When you check the settings in a lot of country tehre is a (no IR) flag in a lot of 5Ghz canals. like: 5200 MHz [40] (20.0 dBm) (no IR)  this "no IR" 

to fix it:

```
country XX: DFS-UNSET
              (2402 - 2494 @ 40), (N/A, 40), (N/A)
              (5170 - 5250 @ 80), (N/A, 40), (N/A)
              (5250 - 5330 @ 80), (N/A, 40), (N/A)
              (5490 - 5730 @ 160), (N/A, 40), (N/A)
              (5735 - 5835 @ 80), (N/A, 40), (N/A)
              (57240 - 63720 @ 2160), (N/A, 40), (N/A)
```
