### ISSUE TITLE
Precompiled .ko?

### ISSUE THREAD

**Issue by colourful-land** [ulli-kroll/mt7610u#56]
I've got TP-LINK Archer T2U. I was thinking if there is a way to get pre-compiled mt7610u.ko - my kernel is a 3.3.2 one in armv5tel arch, but it runs on an embed device (with Debian wheezy) so there isn't much memory capacity to compile my own module. Know this is much to ask. Thanks.

**Comment by ulli-kroll** [comment]
v3.3.2 is very old
It's almost impossible to use this kernel.
Aside form this you can build this module with a cross compiler using common call schema
`make ARCH=$arch CROSS_COMPILER=$gcc`

**Comment by colourful-land** [comment]
Thanks. I close this issue because the difficulty doesn't justify the effort.
