### ISSUE TITLE
Cannnot connect to SSID whose length is over 6 (ETH_ALEN).

### ISSUE THREAD

**Issue by RyojiHARUKI** [ulli-kroll/mt7610u#63]
I found this bug.
Please fix the below "Ssid[ETH_ALEN]" to "Ssid[32]".

"include/rtmp_cmd.h" around line 437:
```
typedef struct __CMD_RTPRIV_IOCTL_80211_CONNECT {

	u8 WpaVer;
	bool FlgIs8021x;
	u8 AuthType;
	//bool FlgIsAuthOpen;

	u8 PairwiseEncrypType;
	u8 GroupwiseEncrypType;

	u8 *Key;
	u32 KeyLen;
	u8 KeyIdx;

	u8 Ssid[ETH_ALEN];
	u32 SsidLen;




	u8 Bssid[ETH_ALEN];

	bool bWpsConnection;
#ifdef DOT11W_PMF_SUPPORT
	bool mfp;
#endif /* DOT11W_PMF_SUPPORT */

} CMD_RTPRIV_IOCTL_80211_CONNECT;

```

**Comment by ulli-kroll** [comment]
> I found this bug.
> Please fix the below "Ssid[ETH_ALEN]" to "Ssid[32]".
> 
You've opened a can of worms here ...
They are more places like that

**Comment by ulli-kroll** [comment]
Issue (hopefully) fixed
These where introduced to remove some compiler warnings

Please check current git

**Comment by RyojiHARUKI** [comment]
Thank you for your modification.
I confirmed the issue is fixed.
