### ISSUE TITLE
USB id issues

### ISSUE THREAD

**Issue by MrEngman** [ulli-kroll/mt7610u#9]
Just been looking at your driver for use with the Raspberry Pi.

There is an issue with the file `os/linux/usb_main_dev.c`. There are two copies of the line `        { USB_DEVICE(0x13B1, 0x003E) }, /* Linksys AE6000 */
` lines 53 and 67.

Also are you sure all the other USB IDs are OK. Looking at other versions of the 7610 driver a couple of the USB IDs are different to several other drivers I've looked at.

Line 64 is `        { USB_DEVICE(0x0586, 0x2425) }, /* Zyxel NWD6505 */` but other drivers show the ID as `0x0586, 0x3425`

Line 69 is `        { USB_DEVICE(0x293c, 0x6702) }, /* Comcast Xfinity KXW02AAA  */` but other drivers show the ID as `0x293c, 0x5702`

EDIT: and Line 61 `        { USB_DEVICE(0x0df6, 0x0076) }, /* Sitecom WLA-3100 */` That USB ID is for an 8188eu device, Sitecom N150 v2. The ID should probably be `0x0df6, 0x0075`

**Comment by ulli-kroll** [comment]
fixed in current git
please pull
